### ISSUE TITLE
[CLI] Investigate switching to click for CLI option processing

### ISSUE THREAD

**Issue by rtamalin** [SUSE/scc-hypervisor-collector#7]
Initially the need to be compatible with the potential Python ecosystem available on SLE 12 SP5 systems, where click was not available in the standard supported repos, limited our choice of CLI option processing to the argparse module.

However is that restriction goes away we may want to consider click again, and it would be good to determine if this is worth doing.

**Comment by mbelur** [comment]
The command line options we have for the tool are simple and we do not use any sub-commands in our tool that requires the need for the click library. In addition, click does not have native support for mutually exclusive options. So we will have to pull in additional dependency: https://github.com/click-contrib/click-option-group which creates additional burden with building the tool in OBS relating to maintenance. As part of this evaluation, we are going to defer/close this issue.

**Comment by rtamalin** [comment]
Let's close this for now - we can reopen later if we want to revisit.
